# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    article:
      uri_prefix: /images
      upload_destination: '%kernel.project_dir%/public/images'
#      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer



#vich_uploader:
#  db_driver: orm
#
#  mappings:
#    article_img:
#      uri_prefix: /img/articles
#      upload_destination: '%kernel.project_dir%/public'
#
#
